// rent-aride-miniapp/src/App.svelte
<script>
  import { onMount } from 'svelte';
  import Router from 'svelte-spa-router';
  import Home from './routes/Home.svelte';
  import Book from './routes/Book.svelte';
  import Rentals from './routes/Rentals.svelte';
  import PaymentFinish from './routes/PaymentFinish.svelte';
  import { allowSystemSnapshot } from './lib/bridge/index.js';
  import { auth, logout } from './lib/stores/auth.js';

  onMount(() => allowSystemSnapshot());

  const routes = {
    '/': Home,
    '/book': Book,
    '/rentals': Rentals,
    '/payment/finish': PaymentFinish,
  };
</script>

<div class="min-h-screen flex flex-col">
  <header class="h-16 w-full bg-stone-700 flex items-center justify-between px-4 fixed top-0 left-0 right-0 z-10">
    <a href="#/" class="text-xl font-bold text-white hover:no-underline">Rent-A-Ride</a>
    <nav class="flex items-center gap-3">
      <a href="#/" class="text-white/90 hover:text-white text-sm">Browse</a>
      <a href="#/book" class="text-white/90 hover:text-white text-sm">Book</a>
      <a href="#/rentals" class="text-white/90 hover:text-white text-sm">My rentals</a>
      {#if $auth?.token}
        <button
          type="button"
          class="rounded border border-white/50 px-3 py-1 text-sm text-white hover:bg-white/10"
          on:click={logout}
        >
          Logout
        </button>
      {/if}
    </nav>
  </header>
  <main class="flex-1 w-full max-w-2xl mx-auto">
    <Router {routes} />
  </main>
</div>

// rent-aride-frontend/src/App.vue
<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router'
import { storeToRefs } from 'pinia'
import { useAuthStore } from '@/stores/auth'

const { user, isLoggedIn, isAdmin } = storeToRefs(useAuthStore())
</script>

<template>
  <div class="min-h-screen flex flex-col">
    <header class="flex items-center justify-between border-b border-gray-200 bg-gray-50 px-6 py-4 dark:border-gray-700 dark:bg-gray-800">
      <RouterLink to="/" class="text-xl font-bold text-gray-900 hover:underline dark:text-white">
        Rent-A-Ride
      </RouterLink>
      <nav class="flex items-center gap-4">
        <RouterLink
          to="/"
          class="rounded px-3 py-2 text-gray-600 hover:bg-gray-200 dark:text-gray-300 dark:hover:bg-gray-700"
          active-class="font-semibold"
        >
          Browse
        </RouterLink>
        <template v-if="isLoggedIn">
          <RouterLink
            to="/rentals/new"
            class="rounded px-3 py-2 text-gray-600 hover:bg-gray-200 dark:text-gray-300 dark:hover:bg-gray-700"
            active-class="font-semibold"
          >
            Book a car
          </RouterLink>
          <RouterLink
            to="/rentals"
            class="rounded px-3 py-2 text-gray-600 hover:bg-gray-200 dark:text-gray-300 dark:hover:bg-gray-700"
            active-class="font-semibold"
          >
            My rentals
          </RouterLink>
          <template v-if="isAdmin">
            <RouterLink
              to="/admin/vehicle-types"
              class="rounded px-3 py-2 text-gray-600 hover:bg-gray-200 dark:text-gray-300 dark:hover:bg-gray-700"
              active-class="font-semibold"
            >
              Vehicle types
            </RouterLink>
            <RouterLink
              to="/admin/amenities"
              class="rounded px-3 py-2 text-gray-600 hover:bg-gray-200 dark:text-gray-300 dark:hover:bg-gray-700"
              active-class="font-semibold"
            >
              Amenities
            </RouterLink>
            <RouterLink
              to="/admin/vehicles"
              class="rounded px-3 py-2 text-gray-600 hover:bg-gray-200 dark:text-gray-300 dark:hover:bg-gray-700"
              active-class="font-semibold"
            >
              Vehicles
            </RouterLink>
          </template>
          <span class="ml-2 text-sm text-gray-500">{{ user?.email }}</span>
          <button
            type="button"
            class="rounded border border-gray-300 px-4 py-2 text-sm hover:bg-gray-100 dark:border-gray-600 dark:hover:bg-gray-700"
            @click="useAuthStore().logout()"
          >
            Logout
          </button>
        </template>
        <template v-else>
          <RouterLink
            to="/login"
            class="rounded px-3 py-2 text-gray-600 hover:bg-gray-200 dark:text-gray-300 dark:hover:bg-gray-700"
            active-class="font-semibold"
          >
            Login
          </RouterLink>
          <RouterLink
            to="/register"
            class="rounded px-3 py-2 text-gray-600 hover:bg-gray-200 dark:text-gray-300 dark:hover:bg-gray-700"
            active-class="font-semibold"
          >
            Register
          </RouterLink>
        </template>
      </nav>
    </header>
    <main class="mx-auto w-full max-w-6xl flex-1 px-6 py-6">
      <RouterView />
    </main>
  </div>
</template>
